### PR TITLE
Update to work with the new curseforge site

### PR DESCRIPTION
**Pull request by mgziminsky**
Fix the urls used to download mods and packs from curseforge to use the correct paths for their new site.

For installing mods, I left it calling the old redirect, but don't know if that's going to work for long. I considered changing it to lookup the slug in the DB, but that's less reliable in case a mod isn't in the db for whatever reason. There does appear to be quite a few missing right now, so the db may be due for a full refresh.

### CODE REVIEW

**Comment by Esgariot** [comment]
I've just tried to download few mods using the latest release and instead of downloading `.jar`s there were a bunch of webpages. Could it be that old curseforge paths are no longer correct?

**Comment by mgziminsky** [comment]
Yes, the current version is broken since the new curseforge site went live. That's what this PR is fixing.

You'll have to wait until this gets merged, or dizzyd releases his own fix.

If you know how, you can build my branch for yourself until an official release is ready.

**Comment by Esgariot** [comment]
I needed to remove everything from `mods/` or it would skip, but except that worked like a charm. Thanks!

**Comment by dizzyd** [comment]
I'll dig into this tomorrow morning! Thanks for submitting.

**Comment by Trolzer** [comment]
any updates on getting this merged?

**Comment by dizzyd** [comment]
I’m traveling at the moment, but hope to get it done tomorrow!

**Comment by dizzyd** [comment]
Thank you @mgziminsky !! All merged in.

**Pull request merged**
